"""users table

Revision ID: 4244923596f7
Revises: 
Create Date: 2020-08-12 12:09:02.320108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4244923596f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users table_email'), 'users table', ['email'], unique=True)
    op.create_index(op.f('ix_users table_username'), 'users table', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users table_username'), table_name='users table')
    op.drop_index(op.f('ix_users table_email'), table_name='users table')
    op.drop_table('users table')
    # ### end Alembic commands ###
